apiVersion: v1
description: An enterprise-grade open-source platform for building, training, and monitoring large scale deep learning applications.
name: polyaxon
version: 1.1.8-rc1
appVersion: 1.1.8-rc1
keywords:
  - deep learning
  - a.i.
  - machine learning
  - infrastructure
sources:
  - https://github.com/polyaxon
home: https://polyaxon.com
icon: https://cdn.polyaxon.com/static/v1/images/logo_small.png
maintainers:
  - name: Polyaxon
    email: contact@polyaxon.com
    url: polyaxon.com
